name: Test

on:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-18.04
    name: Test
    steps:
      - uses: actions/checkout@v2

      - name: Fetch main branch refs for comparison
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/main:refs/remotes/origin/main
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Setup Private NPM Modules Token
        run: npm config set '//registry.npmjs.org/:_authToken' '${NPM_TOKEN}'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn
      - name: Install Node Modules
        run: yarn install --frozen-lockfile
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Run Tests
        run: yarn lerna run test:cov --since origin/main
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}